service: video
runtime: custom
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
vm_health_check:   
  enable_health_check: False 
readiness_check:
  app_start_timeout_sec: 300
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10